### ISSUE TITLE
Is that possible to call 'learn' multiple times?

### ISSUE THREAD

**Issue by PavloPoliakov** [stevenmiller888/mind#15]
Hi,

Is that somehow possible to `learn` your network several times?

From all the examples, it looks like you need to pass an array of `{input, output}` there. However, it would be cool to be able to learn your network several times. So it gets "smarter" and "smarter".

Are there any ways to perform that?

Regards,

**Comment by stevenmiller888** [comment]
@PavelPolyakov Should be possible. Just need to check if the network has already called `.learn` before [this](https://github.com/stevenmiller888/mind/blob/master/lib/index.js#L79) line runs. PRs are welcome :)
