### ISSUE TITLE
The example code always gives ~1

### ISSUE THREAD

**Issue by mikkokam** [stevenmiller888/mind#19]
Problem:
Using the Letters -demo code from Readme.md -- it does not give ~0.5 as expected, but ~1 most of the time.

[(http://codepen.io/mikkokam/pen/730368f3f615bc9930d695cc91b80491?editors=1010)]

**Comment by stevenmiller888** [comment]
Try using the sigmoid activation function instead. 

e.g. https://github.com/stevenmiller888/mind/blob/master/examples/character-recognition/simple/index.js#L49

**Comment by mikkokam** [comment]
Thanks, works!
