### ISSUE TITLE
download() and upload() the Mind

### ISSUE THREAD

**Issue by MadalinaCi** [stevenmiller888/mind#53]
Hi @stevenmiller888 ! 

Thanks a lot for making this public, amazing work and very helpful for beginners. 
I want to use the Mind in predicting the mood of a user based on keystrokes(moment of pressing, not the content). 

As I will have lots of data for training, after training the Mind I would like to download it and use it anytime I need to make a new prediction. I tried to use download() and upload() functions. After downloading the Mind, where can I find it? How do I know what will be the parameter for the upload function?

I am new to nodejs and modules and so on. 

Thank you!

**Comment by stevenmiller888** [comment]
I just created a new [example](https://github.com/stevenmiller888/mind/blob/master/examples/download-upload/index.js) to make downloading/uploading clearer. Let me know if you still have questions after checking that out!
